insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('4','АФГАНИСТАН','Переходное Исламское Государство Афганистан','AF','AFG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('8','АЛБАНИЯ','Республика Албания','AL','ALB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('10','АНТАРКТИДА','','AQ','ATA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('12','АЛЖИР','Алжирская Народная Демократическая Республика','DZ','DZA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('16','АМЕРИКАНСКОЕ САМОА','','AS','ASM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('20','АНДОРРА','Княжество Андорра','AD','AND');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('24','АНГОЛА','Республика Ангола','AO','AGO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('28','АНТИГУА И БАРБУДА','','AG','ATG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('31','АЗЕРБАЙДЖАН','Республика Азербайджан','AZ','AZE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('32','АРГЕНТИНА','Аргентинская Республика','AR','ARG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('36','АВСТРАЛИЯ','','AU','AUS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('40','АВСТРИЯ','Австрийская Республика','AT','AUT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('44','БАГАМЫ','Содружество Багамы','BS','BHS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('48','БАХРЕЙН','Королевство Бахрейн','BH','BHR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('50','БАНГЛАДЕШ','Народная Республика Бангладеш','BD','BGD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('51','АРМЕНИЯ','Республика Армения','AM','ARM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('52','БАРБАДОС','','BB','BRB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('56','БЕЛЬГИЯ','Королевство Бельгия','BE','BEL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('60','БЕРМУДЫ','','BM','BMU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('64','БУТАН','Королевство Бутан','BT','BTN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('68','БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО','Многонациональное Государство Боливия','BO','BOL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('70','БОСНИЯ И ГЕРЦЕГОВИНА','','BA','BIH');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('72','БОТСВАНА','Республика Ботсвана','BW','BWA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('74','ОСТРОВ БУВЕ','','BV','BVT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('76','БРАЗИЛИЯ','Федеративная Республика Бразилия','BR','BRA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('84','БЕЛИЗ','','BZ','BLZ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('86','БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ','','IO','IOT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('90','СОЛОМОНОВЫ ОСТРОВА','','SB','SLB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('92','ВИРГИНСКИЕ ОСТРОВА (БРИТАНСКИЕ)','Британские Виргинские острова','VG','VGB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('96','БРУНЕЙ-ДАРУССАЛАМ','','BN','BRN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('100','БОЛГАРИЯ','Республика Болгария','BG','BGR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('104','МЬЯНМА','Республика Союза Мьянма','MM','MMR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('108','БУРУНДИ','Республика Бурунди','BI','BDI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('112','БЕЛАРУСЬ','Республика Беларусь','BY','BLR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('116','КАМБОДЖА','Королевство Камбоджа','KH','KHM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('120','КАМЕРУН','Республика Камерун','CM','CMR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('124','КАНАДА','','CA','CAN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('132','КАБО-ВЕРДЕ','Республика Кабо-Верде','CV','CPV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('136','ОСТРОВА КАЙМАН','','KY','CYM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('140','ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА','','CF','CAF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('144','ШРИ-ЛАНКА','Демократическая Социалистическая Республика Шри-Ланка','LK','LKA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('148','ЧАД','Республика Чад','TD','TCD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('152','ЧИЛИ','Республика Чили','CL','CHL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('156','КИТАЙ','Китайская Народная Республика','CN','CHN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('158','ТАЙВАНЬ (КИТАЙ)','','TW','TWN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('162','ОСТРОВ РОЖДЕСТВА','','CX','CXR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('166','КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА','','CC','CCK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('170','КОЛУМБИЯ','Республика Колумбия','CO','COL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('174','КОМОРЫ','Союз Коморы','KM','COM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('175','МАЙОТТА','','YT','MYT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('178','КОНГО','Республика Конго','CG','COG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('180','КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','Демократическая Республика Конго','CD','COD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('184','ОСТРОВА КУКА','','CK','COK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('188','КОСТА-РИКА','Республика Коста-Рика','CR','CRI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('191','ХОРВАТИЯ','Республика Хорватия','HR','HRV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('192','КУБА','Республика Куба','CU','CUB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('196','КИПР','Республика Кипр','CY','CYP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('203','ЧЕХИЯ','Чешская Республика','CZ','CZE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('204','БЕНИН','Республика Бенин','BJ','BEN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('208','ДАНИЯ','Королевство Дания','DK','DNK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('212','ДОМИНИКА','Содружество Доминики','DM','DMA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('214','ДОМИНИКАНСКАЯ РЕСПУБЛИКА','','DO','DOM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('218','ЭКВАДОР','Республика Эквадор','EC','ECU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('222','ЭЛЬ-САЛЬВАДОР','Республика Эль-Сальвадор','SV','SLV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('226','ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ','Республика Экваториальная Гвинея','GQ','GNQ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('231','ЭФИОПИЯ','Федеративная Демократическая Республика Эфиопия','ET','ETH');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('232','ЭРИТРЕЯ','Государство Эритрея','ER','ERI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('233','ЭСТОНИЯ','Эстонская Республика','EE','EST');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('234','ФАРЕРСКИЕ ОСТРОВА','','FO','FRO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('238','ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)','','FK','FLK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('239','ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА','','GS','SGS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('242','ФИДЖИ','Республика Фиджи','FJ','FJI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('246','ФИНЛЯНДИЯ','Финляндская Республика','FI','FIN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('248','ЭЛАНДСКИЕ ОСТРОВА','','АХ','ALA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('250','ФРАНЦИЯ','Французская Республика','FR','FRA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('254','ФРАНЦУЗСКАЯ ГВИАНА','','GF','GUF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('258','ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ','','PF','PYF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('260','ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ','','TF','ATF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('262','ДЖИБУТИ','Республика Джибути','DJ','DJI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('266','ГАБОН','Габонская Республика','GA','GAB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('268','ГРУЗИЯ','','GE','GEO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('270','ГАМБИЯ','Республика Гамбия','GM','GMB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('275','ПАЛЕСТИНА, ГОСУДАРСТВО','Государство Палестина','PS','PSE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('276','ГЕРМАНИЯ','Федеративная Республика Германия','DE','DEU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('288','ГАНА','Республика Гана','GH','GHA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('292','ГИБРАЛТАР','','GI','GIB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('296','КИРИБАТИ','Республика Кирибати','KI','KIR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('300','ГРЕЦИЯ','Греческая Республика','GR','GRC');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('304','ГРЕНЛАНДИЯ','','GL','GRL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('308','ГРЕНАДА','','GD','GRD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('312','ГВАДЕЛУПА','','GP','GLP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('316','ГУАМ','','GU','GUM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('320','ГВАТЕМАЛА','Республика Гватемала','GT','GTM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('324','ГВИНЕЯ','Гвинейская Республика','GN','GIN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('328','ГАЙАНА','Республика Гайана','GY','GUY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('332','ГАИТИ','Республика Гаити','HT','HTI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('334','ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД','','HM','HMD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('336','ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)','','VA','VAT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('340','ГОНДУРАС','Республика Гондурас','HN','HND');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('344','ГОНКОНГ','Специальный административный регион Китая Гонконг','HK','HKG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('348','ВЕНГРИЯ','Венгрия','HU','HUN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('352','ИСЛАНДИЯ','Республика Исландия','IS','ISL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('356','ИНДИЯ','Республика Индия','IN','IND');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('360','ИНДОНЕЗИЯ','Республика Индонезия','ID','IDN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('364','ИРАН (ИСЛАМСКАЯ РЕСПУБЛИКА)','Исламская Республика Иран','IR','IRN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('368','ИРАК','Республика Ирак','IQ','IRQ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('372','ИРЛАНДИЯ','','IE','IRL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('376','ИЗРАИЛЬ','Государство Израиль','IL','ISR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('380','ИТАЛИЯ','Итальянская Республика','IT','ITA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('384','КОТ Д'|| '''' || 'ИВУАР','Республика Кот д'|| '''' || 'Ивуар','CI','CIV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('388','ЯМАЙКА','','JM','JAM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('392','ЯПОНИЯ','','JP','JPN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('398','КАЗАХСТАН','Республика Казахстан','KZ','KAZ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('400','ИОРДАНИЯ','Иорданское Хашимитское Королевство','JO','JOR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('404','КЕНИЯ','Республика Кения','KE','KEN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('408','КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','Корейская Народно-Демократическая Республика','KP','PRK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('410','КОРЕЯ, РЕСПУБЛИКА','Республика Корея','KR','KOR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('414','КУВЕЙТ','Государство Кувейт','KW','KWT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('417','КИРГИЗИЯ','Киргизская Республика','KG','KGZ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('418','ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','','LA','LAO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('422','ЛИВАН','Ливанская Республика','LB','LBN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('426','ЛЕСОТО','Королевство Лесото','LS','LSO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('428','ЛАТВИЯ','Латвийская Республика','LV','LVA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('430','ЛИБЕРИЯ','Республика Либерия','LR','LBR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('434','ЛИВИЯ','Государство Ливия','LY','LBY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('438','ЛИХТЕНШТЕЙН','Княжество Лихтенштейн','LI','LIE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('440','ЛИТВА','Литовская Республика','LT','LTU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('442','ЛЮКСЕМБУРГ','Великое Герцогство Люксембург','LU','LUX');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('446','МАКАО','Специальный административный регион Китая Макао','MO','MAC');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('450','МАДАГАСКАР','Республика Мадагаскар','MG','MDG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('454','МАЛАВИ','Республика Малави','MW','MWI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('458','МАЛАЙЗИЯ','','MY','MYS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('462','МАЛЬДИВЫ','Мальдивская Республика','MV','MDV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('466','МАЛИ','Республика Мали','ML','MLI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('470','МАЛЬТА','Республика Мальта','MT','MLT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('474','МАРТИНИКА','','MQ','MTQ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('478','МАВРИТАНИЯ','Исламская Республика Мавритания','MR','MRT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('480','МАВРИКИЙ','Республика Маврикий','MU','MUS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('484','МЕКСИКА','Мексиканские Соединенные Штаты','MX','MEX');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('492','МОНАКО','Княжество Монако','MC','MCO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('496','МОНГОЛИЯ','','MN','MNG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('498','МОЛДОВА, РЕСПУБЛИКА','Республика Молдова','MD','MDA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('499','ЧЕРНОГОРИЯ','','ME','MNE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('500','МОНТСЕРРАТ','','MS','MSR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('504','МАРОККО','Королевство Марокко','MA','MAR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('508','МОЗАМБИК','Республика Мозамбик','MZ','MOZ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('512','ОМАН','Султанат Оман','OM','OMN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('516','НАМИБИЯ','Республика Намибия','NA','NAM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('520','НАУРУ','Республика Науру','NR','NRU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('524','НЕПАЛ','Федеративная Демократическая Республика Непал','NP','NPL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('528','НИДЕРЛАНДЫ','Королевство Нидерландов','NL','NLD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('531','КЮРАСАО','','CW','CUW');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('533','АРУБА','','AW','ABW');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('534','СЕН-МАРТЕН (нидерландская часть)','','SX','SXM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('535','БОНЭЙР, СИНТ-ЭСТАТИУС И САБА','','BQ','BES');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('540','НОВАЯ КАЛЕДОНИЯ','','NC','NCL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('548','ВАНУАТУ','Республика Вануату','VU','VUT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('554','НОВАЯ ЗЕЛАНДИЯ','','NZ','NZL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('558','НИКАРАГУА','Республика Никарагуа','NI','NIC');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('562','НИГЕР','Республика Нигер','NE','NER');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('566','НИГЕРИЯ','Федеративная Республика Нигерия','NG','NGA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('570','НИУЭ','Республика Ниуэ','NU','NIU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('574','ОСТРОВ НОРФОЛК','','NF','NFK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('578','НОРВЕГИЯ','Королевство Норвегия','NO','NOR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('580','СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА','Содружество Северных Марианских островов','MP','MNP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('581','МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ','','UM','UMI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('583','МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ','Федеративные штаты Микронезии','FM','FSM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('584','МАРШАЛЛОВЫ ОСТРОВА','Республика Маршалловы Острова','MH','MHL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('585','ПАЛАУ','Республика Палау','PW','PLW');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('586','ПАКИСТАН','Исламская Республика Пакистан','PK','PAK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('591','ПАНАМА','Республика Панама','PA','PAN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('598','ПАПУА-НОВАЯ ГВИНЕЯ','Независимое Государство Папуа Новая Гвинея','PG','PNG');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('600','ПАРАГВАЙ','Республика Парагвай','PY','PRY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('604','ПЕРУ','Республика Перу','PE','PER');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('608','ФИЛИППИНЫ','Республика Филиппины','PH','PHL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('612','ПИТКЕРН','','PN','PCN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('616','ПОЛЬША','Республика Польша','PL','POL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('620','ПОРТУГАЛИЯ','Португальская Республика','PT','PRT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('624','ГВИНЕЯ-БИСАУ','Республика Гвинея-Бисау','GW','GNB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('626','ТИМОР-ЛЕСТЕ','Демократическая Республика Тимор-Лесте','TL','TLS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('630','ПУЭРТО-РИКО','','PR','PRI');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('634','КАТАР','Государство Катар','QA','QAT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('638','РЕЮНЬОН','','RE','REU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('642','РУМЫНИЯ','','RO','ROU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('643','РОССИЯ','Российская Федерация','RU','RUS');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('646','РУАНДА','Руандийская Республика','RW','RWA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('652','СЕН-БАРТЕЛЕМИ','','BL','BLM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('654','СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ','','SH','SHN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('659','СЕНТ-КИТС И НЕВИС','','KN','KNA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('660','АНГИЛЬЯ','','AI','AIA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('662','СЕНТ-ЛЮСИЯ','','LC','LCA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('663','СЕН-МАРТЕН (французская часть)','','MF','MAF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('666','СЕН-ПЬЕР И МИКЕЛОН','','PM','SPM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('670','СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ','','VC','VCT');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('674','САН-МАРИНО','Республика Сан-Марино','SM','SMR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('678','САН-ТОМЕ И ПРИНСИПИ','Демократическая Республика Сан-Томе и Принсипи','ST','STP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('682','САУДОВСКАЯ АРАВИЯ','Королевство Саудовская Аравия','SA','SAU');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('686','СЕНЕГАЛ','Республика Сенегал','SN','SEN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('688','СЕРБИЯ','Республика Сербия','RS','SRB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('690','СЕЙШЕЛЫ','Республика Сейшелы','SC','SYC');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('694','СЬЕРРА-ЛЕОНЕ','Республика Сьерра-Леоне','SL','SLE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('702','СИНГАПУР','Республика Сингапур','SG','SGP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('703','СЛОВАКИЯ','Словацкая Республика','SK','SVK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('704','ВЬЕТНАМ','Социалистическая Республика Вьетнам','VN','VNM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('705','СЛОВЕНИЯ','Республика Словения','SI','SVN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('706','СОМАЛИ','Федеративная Республика Сомали','SO','SOM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('710','ЮЖНАЯ АФРИКА','Южно-Африканская Республика','ZA','ZAF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('716','ЗИМБАБВЕ','Республика Зимбабве','ZW','ZWE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('724','ИСПАНИЯ','Королевство Испания','ES','ESP');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('728','ЮЖНЫЙ СУДАН','Республика Южный Судан','SS','SSD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('729','СУДАН','Республика Судан','SD','SDN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('732','ЗАПАДНАЯ САХАРА','','EH','ESH');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('740','СУРИНАМ','Республика Суринам','SR','SUR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('744','ШПИЦБЕРГЕН И ЯН МАЙЕН','','SJ','SJM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('748','ЭСВАТИНИ','Королевство Эсватини','SZ','SWZ');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('752','ШВЕЦИЯ','Королевство Швеция','SE','SWE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('756','ШВЕЙЦАРИЯ','Швейцарская Конфедерация','CH','CHE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('760','СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА','','SY','SYR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('762','ТАДЖИКИСТАН','Республика Таджикистан','TJ','TJK');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('764','ТАИЛАНД','Королевство Таиланд','TH','THA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('768','ТОГО','Тоголезская Республика','TG','TGO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('772','ТОКЕЛАУ','','TK','TKL');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('776','ТОНГА','Королевство Тонга','TO','TON');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('780','ТРИНИДАД И ТОБАГО','Республика Тринидад и Тобаго','TT','TTO');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('784','ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ','','AE','ARE');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('788','ТУНИС','Тунисская Республика','TN','TUN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('792','ТУРЦИЯ','Турецкая Республика','TR','TUR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('795','ТУРКМЕНИСТАН','Туркменистан','TM','TKM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('796','ОСТРОВА ТЕРКС И КАЙКОС','','TC','TCA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('798','ТУВАЛУ','','TV','TUV');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('800','УГАНДА','Республика Уганда','UG','UGA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('804','УКРАИНА','','UA','UKR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('807','СЕВЕРНАЯ МАКЕДОНИЯ','Республика Северная Македония','MK','MKD');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('818','ЕГИПЕТ','Арабская Республика Египет','EG','EGY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('826','СОЕДИНЕННОЕ КОРОЛЕВСТВО','Соединенное Королевство Великобритании и Северной Ирландии','GB','GBR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('831','ГЕРНСИ','','GG','GGY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('832','ДЖЕРСИ','','JE','JEY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('833','ОСТРОВ МЭН','','IM','IMN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('834','ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА','Объединенная Республика Танзания','TZ','TZA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('840','СОЕДИНЕННЫЕ ШТАТЫ','Соединенные Штаты Америки','US','USA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('850','ВИРГИНСКИЕ ОСТРОВА (США)','Виргинские острова Соединенных Штатов','VI','VIR');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('854','БУРКИНА-ФАСО','','BF','BFA');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('858','УРУГВАЙ','Восточная Республика Уругвай','UY','URY');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('860','УЗБЕКИСТАН','Республика Узбекистан','UZ','UZB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('862','ВЕНЕСУЭЛА (БОЛИВАРИАНСКАЯ РЕСПУБЛИКА)','Боливарианская Республика Венесуэла','VE','VEN');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('876','УОЛЛИС И ФУТУНА','','WF','WLF');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('882','САМОА','Независимое Государство Самоа','WS','WSM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('887','ЙЕМЕН','Йеменская Республика','YE','YEM');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('894','ЗАМБИЯ','Республика Замбия','ZM','ZMB');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('895','АБХАЗИЯ','Республика Абхазия','AB','ABH');
insert into h2020.oksm (s_code, s_short_name, s_full_name, s_alfa2, s_alfa3) values ('896','ЮЖНАЯ ОСЕТИЯ','Республика Южная Осетия','OS','OST');
update h2020.oksm
   set s_code = lpad(s_code, 3, '0');
commit;