--liquibase formatted sql

--changeset User1:7

insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AUD','36','Австралийский доллар','Австралия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AZN','944','Азербайджанский манат','Азербайджанская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ALL','8','Албанский лек','Республика Албания');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('DZD','12','Алжирский динар','Алжирская Народная Демократическая Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AOA','973','Ангольская кванза','Народная Республика Ангола');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ARS','32','Аргентинское песо','Аргентинская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AMD','51','Армянский драм','Республика Армения');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AWG','533','Арубанский флорин','Остров Аруба');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AFN','971','Афганский афгани','Исламское Государство Афганистан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BSD','44','Багамский доллар','Содружество Багамских Островов');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BDT','50','Бангладешская така','Народная Республика Бангладеш');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BBD','52','Барбадосский доллар','Барбадос');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BHD','48','Бахрейнский динар','Государство Бахрейн');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BZD','84','Белизский доллар','Белиз');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BYN','933','Белорусский рубль','Республика Беларусь');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BMD','60','Бермудский доллар','Бермудские Острова');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BGN','975','Болгарский лев','Республика Болгария');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BOB','68','Боливийский боливиано','Республика Боливия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BWP','72','Ботсванская пула','Республика Ботсвана');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BRL','986','Бразильский реал','Федеративная Республика Бразилия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BND','96','Брунейский доллар','Бруней-Даруссалам');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BIF','108','Бурундийский франк','Республика Бурунди');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('VUV','548','Вату Вануату','Республика Вануату');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('HUF','348','Венгерский форинт','Венгерская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KRW','410','Вона Республики Корея','Республика Корея');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('XCD','951','Восточно-карибский доллар','Денежная единица Организации Восточно-Карибских государств: Ангилья; Антигуа и Барбуда; Гренада; Доминика; Монсеррат; Сент-Винсент и Гренадины; Сент-Китс и Невис; Сент-Люсия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('VND','704','Вьетнамский донг','Народная Республика Вьетнам');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('HTG','332','Гаитянский гурд','Республика Гаити');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GYD','328','Гайанский доллар','Кооперативная Республика Гайана');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GMD','270','Гамбийский даласи','Республика Гамбия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GHS','936','Ганский седи','Республика Гана');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GTQ','320','Гватемальский кетсаль','Республика Гватемала');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GNF','324','Гвинейский франк','Гвинейская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GGP','0','Гернсийский фунт','Гернси');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GIP','292','Гибралтарский фунт','Гибралтар (брит.)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('HNL','340','Гондурасская лемпира','Республика Гондурас');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('HKD','344','Гонконгский доллар','Сянган (Гонконг)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GEL','981','Грузинский лари','Республика Грузия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('DKK','208','Датская крона','Королевство Дания');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MKD','807','Денар Республики Македония','Бывшая Союзная Республика Македония');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('JEP','0','Джерсийский фунт','Джерси');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('AED','784','Дирхам ОАЭ','Объединенные Арабские Эмираты');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('STN','930','Добра Сан-Томе и Принсипи','Демократическая Республика Сан-Томе и Принсипи');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KID','0','Доллар Кирибати','Республика Кирибати');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NAD','516','Доллар Намибии','Намибия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('USD','840','Доллар США','Соединенные Штаты Америки (США)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TVD','0','Доллар Тувалу','Тувалу');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('DOP','214','Доминиканское песо','Доминиканская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('EUR','978','ЕВРО','Европейский Союз');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('EGP','818','Египетский фунт','Арабская Республика Египет (АРЕ)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('COU','970','Единица реальной стоимости','Республика Колумбия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ZMW','967','Замбийская квача новая','Республика Замбия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('INR','356','Индийская рупия','Республика Индия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('IDR','360','Индонезийская рупия','Республика Индонезия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('JOD','400','Иорданский динар','Иорданское Хашимитское Королевство');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('IQD','368','Иракский динар','Иракская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('IRR','364','Иранский риал','Исламская Республика Иран (ИРИ)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ISK','352','Исландская крона','Республика Исландия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('YER','886','Йеменский риал','Республика Йемен');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KZT','398','Казахстанский тенге','Республика Казахстан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KYD','136','Каимановых островов доллар','Острова Кайман');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KHR','116','Камбоджийский риель','Государство Камбоджа');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CAD','124','Канадский доллар','Канада');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('QAR','634','Катарский риал','Государство Катар');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KES','404','Кенийский шиллинг','Республика Кения');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PGK','598','Кина Папуа - Новая гвинея','Папуа-Новая Гвинея');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LAK','418','Кип Лаосской НДР','Лаосская Народно-Демократическая Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KGS','417','Киргизский сом','Киргизская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CNY','156','Китайский юань Жэньминьби','Китайская Народная Республика (КНР)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('COP','170','Колумбийский песо','Республика Колумбия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BAM','977','Конвертируемая марка','Босния и Герцеговина');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CUC','931','Конвертируемое песо','Республика Куба');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CDF','976','Конголезский франк','Демократическая Республика Конго');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CRC','188','Костариканский колон','Республика Коста-Рика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CUP','192','Кубинский песо','Республика Куба');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KWD','414','Кувейтский динар','Государство Кувейт');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MMK','104','Кьят Мьянма','Союз Мьянма');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LRD','430','Либерийский доллар','Республика Либерия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LBP','422','Ливанский фунт','Ливанская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LYD','434','Ливийский динар','Социалистическая Народная Ливийская Арабская Джамахирия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LSL','426','Лоти Лесото','Королевство Лесото');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MUR','480','Маврикийская рупия','Маврикий');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MRU','929','Мавританская угия','Исламская Республика Мавритания');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MWK','454','Малавийская квача','Республика Малави');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MGA','969','Малагасийский ариари','Демократическая Республика Мадагаскар');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MYR','458','Малайзийский ринггит','Малайзия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MVR','462','Мальдивская руфия','Мальдивская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MAD','504','Марокканский дирхам','Королевство Марокко');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MXN','484','Мексиканский песо','Мексиканские Соединенные Штаты');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MZN','943','Мозамбикский метикал','Народная Республика Мозамбик (НРМ)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MDL','498','Молдавский лей','Республика Молдова');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MNT','496','Монгольский тугрик','Монголия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('BTN','64','Нгултрум Бутана','Королевство Бутан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NPR','524','Непальская рупия','Королевство Непал');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NGN','566','Нигерийская найра','Федеративная Республика Нигерия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ANG','532','Нидерландский антильский гульден','Кюрасао');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NIO','558','Никарагуанская золотая кордоба','Республика Никарагуа');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NZD','554','Новозеландский доллар','Новая Зеландия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ILS','376','Новый израильский шекель','Государство Израиль');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TWD','901','Новый тайваньский доллар','Тайвань (в составе Китая)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TMT','934','Новый туркменский манат','Туркменистан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('NOK','578','Норвежская крона','Королевство Норвегия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('OMR','512','Оманский риал','Султанат Оман');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PKR','586','Пакистанская рупия','Исламская Республика Пакистан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PAB','590','Панамский бальбоа','Республика Панама');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PYG','600','Парагвайский гуарани','Республика Парагвай');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('MOP','446','Патака Макао','Аомынь (Макао)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PEN','604','Перуанский новый соль','Республика Перу');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PLN','985','Польский злотый','Польская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('RUB','643','Российский рубль','Российская Федерация');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('RWF','646','Руандийский франк','Руандийская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('RON','946','Румынский лей','Республика Румыния');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SVC','222','Сальвадорский колон','Республика Эль-Сальвадор');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('WST','882','Самоа тала','Западное Самоа');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SAR','682','Саудовский риял','Королевство Саудовская Аравия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SZL','748','Свазилендский лилангени','Королевство Свазиленд');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('XDR','960','СДР (спец. прав заим-я)','МВФ (Международный валютный фонд)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KPW','408','Северокорейская вона','Корейская Народно-Демократическая Республика (КНДР)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SCR','690','Сейшельская рупия','Республика Сейшельские Острова');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('RSD','941','Сербский динар','Сербия и Черногория');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SGD','702','Сингапурский доллар','Республика Сингапур');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SYP','760','Сирийский фунт','Сирийская Арабская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SBD','90','Соломоновых островов доллар','Соломоновы Острова');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SOS','706','Сомалийский шиллинг','Сомалийская Демократическая Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('VES','928','Суверенный боливар','Республика Венесуэла');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SDG','938','Суданский фунт','Республика Судан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SRD','968','Суринамский доллар','Республика Суринам');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SLL','694','Сьерра-Леонский леоне','Республика Сьерра-Леоне');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TJS','972','Таджикский сомони','Республика Таджикистан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('THB','764','Тайландский бат','Королевство Таиланд');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TZS','834','Танзанийский шиллинг','Объединенная Республика Танзания (ОРТ)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TOP','776','Тонганская паанга','Королевство Тонга');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TTD','780','Тринидада и Тобаго доллар','Республика Тринидад и Тобаго');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TND','788','Тунисский динар','Тунисская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('TRY','949','Турецкая лира','Турецкая Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('UGX','800','Угандийский шиллинг','Республика Уганда');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('UZS','860','Узбекский сум','Республика Узбекистан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('UAH','980','Украинская гривна','Украина');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('UYU','858','Уругвайские песо','Восточная Республика Уругвай');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('UYI','940','Уругвайское песо в индексированных единицах','Восточная Республика Уругвай');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('FJD','242','Фиджийский доллар','Республика Фиджи');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('PHP','608','Филиппинское песо','Республика Филиппины');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('FKP','238','Фолклендский фунт','Фолклендские (Мальвинские) острова (спорн.брит/арг.)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('DJF','262','Франк Джибути','Республика Джибути');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('KMF','174','Франк Коморских островов','Федеральная Исламская Республика Коморские острова');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('XAF','950','Франк КФА ВЕАС','Габон, Камерун, Конго, Центрально-Африканская Республика, Чад, Экваториальная Гвинея.');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('XOF','952','Франк КФА ВСЕАО','Бенин, Буркина-Фасо, Гвинея-Бисау, Кот д'|| '''' || 'Ивуар, Мали, Нигер, Сенегал, Того.');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('XPF','953','Французский тихоокеанский Франк','Французская Полинезия, Новая Каледония, Уоллис и Футуна.');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SHP','654','Фунт о-ва Святой Елены','Остров Святой Елены (брит.)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('GBP','826','Фунт стерлингов','Соединенное Королевство Великобритании и Северной Ирландии');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('HRK','191','Хорватская куна','Республика Хорватия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CZK','203','Чешская крона','Чешская Республика');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CLP','152','Чилийские песо','Республика Чили');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SEK','752','Шведская крона','Королевство Швеция');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CHF','756','Швейцарский франк','Швейцарская Конфедерация');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('LKR','144','Шри-ланкийская рупия','Демократическая Социалистическая Республика Шри-Ланка');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ERN','232','Эритрейская накфа','Эритрея');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('CVE','132','Эскудо Кабо-Верде','Республика Кабо-Верде');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ETB','230','Эфиопский быр','Эфиопия');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('ZAR','710','Южноафриканский рэнд','Южно-Африканская Республика (ЮАР)');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('SSP','728','Южносуданский фунт','Южный Судан');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('JMD','388','Ямайский доллар','Ямайка');
insert into h2020.okv (charcode, numcode, s_name_currency, s_name_country) values ('JPY','392','Японская йена','Япония');
update h2020.okv
   set numcode = lpad(numcode, 3, '0');
commit;